name: VIPCommands
author: SirMiner
description: Commands for VIPs
version: 1.0dev
main: SirMiner\Main
api: [3.0.0]
commands:
  fly:
    description: "Enable or disable flight"
  gmc:
    description: "Set gamemode to creative"
  gms:
    description: "Set gamemode to survival"
permissions: 
     vip.fly:
        default: op
     vip.gamemodes:
         default: op